#!/bin/bash
curl -sL ransomwhat.telemetry.ltd/posts | jq -r '.[] | .post_title, .group_name, .discovered' >  feedRSSdl
IFS=
valeur_a_verifier1=$(cat feedRSSdl | tail -n 1 )
date=$(tail -n 4 monitoring.xml | head -n 1 | cut  -c 10-35 )
grep -A 60 "$date" feedRSSdl | sed '1d' > feedRSSdl2
#permet de retirer les étoiles de la veille de certain ransomware qui bug avec le echo de la création de tableau.
sed -i 's/\*/\\*/g' feedRSSdl feedRSSdl2

if [ -f "monitoring.xml" ] && [ $valeur_a_verifier1 = $date ];then
        exit 1
        elif [ -f "monitoring.xml" ] && [ $valeur_a_verifier1 != $date ];then
        sed -i '$d' monitoring.xml
        sed -i '$d' monitoring.xml
        file="feedRSSdl2"
        while [ "$(wc -l < "$file")" -gt 0 ];do
        IFS=$'\n'
        declare -a valeurs
        valeurs=($(head -n 3 feedRSSdl2))
        # création des feedsRSS
        echo "<item>" >> monitoring.xml
        echo "<title>${valeurs[0]}</title>" >> monitoring.xml
        echo "<description>${valeurs[1]}</description>" >> monitoring.xml
        echo "<link>http://ransomwhat.telemetry.ltd/posts</link>" >> monitoring.xml
        echo "<pubDate>${valeurs[2]}</pubDate>" >> monitoring.xml
        echo "</item>" >> monitoring.xml
        sed -i '1,3d' feedRSSdl2
        done
        # remplace & par &amp, sinon bug xml
        sed -i -e 's/&/\&amp;/g' -e 's/<em>//g' -e 's/<\/em>//g' -e 's/<strong>//g' -e 's/<\/a>//g' monitoring.xml
        echo "</channel>" >> monitoring.xml
        echo "</rss>" >> monitoring.xml
        rm feedRSSdl2 feedRSSdl
        timeout 600 python3 -m http.server 8555 --bind 127.0.0.1
        exit 1
else
#creation du xml.
    echo "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>" > monitoring.xml
    echo "<rss version=\"2.0\">" >> monitoring.xml
    echo "<channel>" >> monitoring.xml
    echo "<title>RANSOMWHAT</title>" >> monitoring.xml
    echo "<link>http://ransomwhat.telemetry.ltd/posts</link>" >> monitoring.xml
    echo "<description>Les nouveaux ransomware</description>" >> monitoring.xml
file="feedRSSdl"
        while [ "$(wc -l < "$file")" -gt 0 ];do
        IFS=$'\n'
# déclare un tableau et recupère victime, groupe et date
        declare -a valeurs
        valeurs=($(head -n 3 feedRSSdl))
# création des feedsRSS
        echo "<item>" >> monitoring.xml
        echo "<title>${valeurs[0]}</title>" >> monitoring.xml
        echo "<description>${valeurs[1]}</description>" >> monitoring.xml
        echo "<link>http://ransomwhat.telemetry.ltd/posts</link>" >> monitoring.xml
        echo "<pubDate>${valeurs[2]}</pubDate>" >> monitoring.xml
        echo "</item>" >> monitoring.xml
        sed -i '1,3d' feedRSSdl
        done
        # remplace & par &amp, sinon bug xml
        sed -i -e 's/&/\&amp;/g' -e 's/<em>//g' -e 's/<\/em>//g' -e 's/<strong>//g' -e 's/<\/a>//g' monitoring.xml
        echo "</channel>" >> monitoring.xml
        echo "</rss>" >> monitoring.xml
# http.server actif 10 minutes
        rm feedRSSdl2 feedRSSdl
        timeout 600 python3 -m http.server 8555 --bind 127.0.0.1
fi
